### ISSUE TITLE
Copyedit

### ISSUE THREAD

**Issue by rochelleterman** [plsc-31101/13-APIs#1]

**Comment by GiacomoRamos** [comment]
1-APIs: 67f8652bdd606fcce6ca76c6c20e43a51f6e41b1

2-RTweet:

- 255567795f9d8575f95be784026607b3ba40fdb6
- edccb96fa6ee8787feaa609046bc11a8d4425378
- d6a03c857be7601255679d1b8d44f8dc084f6d9e

3-Queries: d0ed8dfd2582616704cc6ce99c13c28abf946aaa

4-Solutions: 87dacb830caf44408e2a34185593d375006c0975
